(#2) feature 매칭 대기/매칭 완료를 구현한다.
zolmeet/meeting-server pull request #5
Opened 2022-05-15 10:12 UTC by JxxHxxx

2022-05-16 23:22 UTC, TheDevLuffy requested changes
코드 좀 봤는데 잘 구현해주셨는데요.
궁금한 점 몇 개 코멘트 남겨두었으니 확인 부탁드려요

2022-05-16 23:22 UTC, TheDevLuffy commented on src/main/java/com/zolmeet/zolmeet/domain/PendingMember.java
> +public class PendingMember {
Member 와 Matching 에서 모두 매칭에 대한 상태를 알고 있다면 둘 간의 싱크도 신경써야하니 관리가 복잡하지 않을까요?

2022-05-16 23:22 UTC, TheDevLuffy commented on src/test/java/com/zolmeet/zolmeet/domain/CompletedMembersTest.java
> +    Member male = new Member("B335129", Gender.MALE, "01046577199");
해당 테스트에서 사용되는 것으로 보이는데 private 접근제어자를 사용하면 더 명확하게 의도를 나타낼 수 있지 않을까요?

2022-05-16 23:22 UTC, TheDevLuffy commented on src/test/java/com/zolmeet/zolmeet/domain/MemberTest.java
> +    void studentIdFormat() {
도메인의 요구사항에 맞게 테스트를 잘 작성해주신 것 같아요 👍👍

2022-05-16 23:22 UTC, TheDevLuffy commented on src/main/java/com/zolmeet/zolmeet/domain/Member.java
> +    public List<String> matchingHistory = new ArrayList<>();
생성자 내에서 초기화 해도 괜찮자 않을까요?

2022-05-16 23:22 UTC, TheDevLuffy commented on src/main/java/com/zolmeet/zolmeet/domain/Member.java
> +    public List<String> matchingHistory = new ArrayList<>();
필드명은 MatchingHistory 인데 Member 객체가 가지고 있는 것은 어색하지 않나요 ?

2022-05-16 23:22 UTC, TheDevLuffy commented on src/main/java/com/zolmeet/zolmeet/domain/Member.java
> +    public List<String> matchingHistory = new ArrayList<>();
String 대신 조금 더 풍부하게 표현할 수 있는 객체를 이용해봐도 좋을 것 같아요

2022-05-16 23:22 UTC, TheDevLuffy commented on src/main/java/com/zolmeet/zolmeet/domain/PendingMember.java
> +    public CompletedMembers match(PendingMember partner) {
파라미터 네이밍 변경 👍👍

2022-05-16 23:43 UTC, TheDevLuffy commented on src/main/java/com/zolmeet/zolmeet/domain/PendingMember.java
> +public class PendingMember {
양방향으로 의존하는 연관관계는 지양하는게 좋습니다

좀 길긴한데 객체지향 관련해서 참고 영상 첨부해둘께요. 
https://youtu.be/dJ5C4qRqAgA

2022-05-18 10:28 UTC, JxxHxxx commented
너무 어려워요.

2022-05-18 10:29 UTC, closed without merging